'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SVModel
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SVModel.IEstabilidad")>  _
    Public Interface IEstabilidad
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEstabilidad/DoWork", ReplyAction:="http://tempuri.org/IEstabilidad/DoWorkResponse")>  _
        Sub DoWork()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEstabilidad/DoWork", ReplyAction:="http://tempuri.org/IEstabilidad/DoWorkResponse")>  _
        Function DoWorkAsync() As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEstabilidad/Recomendacion", ReplyAction:="http://tempuri.org/IEstabilidad/RecomendacionResponse")>  _
        Function Recomendacion() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEstabilidad/Recomendacion", ReplyAction:="http://tempuri.org/IEstabilidad/RecomendacionResponse")>  _
        Function RecomendacionAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEstabilidad/Pozo", ReplyAction:="http://tempuri.org/IEstabilidad/PozoResponse")>  _
        Function Pozo( _
                    ByVal Ptr_min As Double,  _
                    ByVal Ptr_max As Double,  _
                    ByVal Ptr_num As Integer,  _
                    ByVal Pwh_Min As Double,  _
                    ByVal Pwh_Max As Double,  _
                    ByVal Pwh_num As Integer,  _
                    ByVal Qgi_min As Double,  _
                    ByVal Qgi_max As Double,  _
                    ByVal Qgi_num As Integer,  _
                    ByVal Dvalve_min As Double,  _
                    ByVal Dvalve_max As Double,  _
                    ByVal Dvalve_num As Integer,  _
                    ByVal DiaVal_min As Double,  _
                    ByVal DiaVal_max As Double,  _
                    ByVal DiaVal_num As Integer,  _
                    ByVal Wc_min As Double,  _
                    ByVal Wc_max As Double,  _
                    ByVal Wc_num As Integer,  _
                    ByVal Cd As Double,  _
                    ByVal Ptr_Act As Double,  _
                    ByVal Pwh_Act As Double,  _
                    ByVal Qgi_Act As Double,  _
                    ByVal Dvalve_Act As Double,  _
                    ByVal DiaValve_Act As Double,  _
                    ByVal Wc_Act As Double,  _
                    ByVal Caso As Integer,  _
                    ByVal Metodologia As Integer) As ModelosEstabilidad.SVModel.EstabilidadDePozosParametros_Estabilidad()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEstabilidad/Pozo", ReplyAction:="http://tempuri.org/IEstabilidad/PozoResponse")>  _
        Function PozoAsync( _
                    ByVal Ptr_min As Double,  _
                    ByVal Ptr_max As Double,  _
                    ByVal Ptr_num As Integer,  _
                    ByVal Pwh_Min As Double,  _
                    ByVal Pwh_Max As Double,  _
                    ByVal Pwh_num As Integer,  _
                    ByVal Qgi_min As Double,  _
                    ByVal Qgi_max As Double,  _
                    ByVal Qgi_num As Integer,  _
                    ByVal Dvalve_min As Double,  _
                    ByVal Dvalve_max As Double,  _
                    ByVal Dvalve_num As Integer,  _
                    ByVal DiaVal_min As Double,  _
                    ByVal DiaVal_max As Double,  _
                    ByVal DiaVal_num As Integer,  _
                    ByVal Wc_min As Double,  _
                    ByVal Wc_max As Double,  _
                    ByVal Wc_num As Integer,  _
                    ByVal Cd As Double,  _
                    ByVal Ptr_Act As Double,  _
                    ByVal Pwh_Act As Double,  _
                    ByVal Qgi_Act As Double,  _
                    ByVal Dvalve_Act As Double,  _
                    ByVal DiaValve_Act As Double,  _
                    ByVal Wc_Act As Double,  _
                    ByVal Caso As Integer,  _
                    ByVal Metodologia As Integer) As System.Threading.Tasks.Task(Of ModelosEstabilidad.SVModel.EstabilidadDePozosParametros_Estabilidad())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEstabilidad/Mapa", ReplyAction:="http://tempuri.org/IEstabilidad/MapaResponse")>  _
        Function Mapa( _
                    ByVal Ptr_min As Double,  _
                    ByVal Ptr_max As Double,  _
                    ByVal Ptr_num As Integer,  _
                    ByVal Pwh_Min As Double,  _
                    ByVal Pwh_Max As Double,  _
                    ByVal Pwh_num As Integer,  _
                    ByVal Qgi_min As Double,  _
                    ByVal Qgi_max As Double,  _
                    ByVal Qgi_num As Integer,  _
                    ByVal Dvalve_min As Double,  _
                    ByVal Dvalve_max As Double,  _
                    ByVal Dvalve_num As Integer,  _
                    ByVal DiaVal_min As Double,  _
                    ByVal DiaVal_max As Double,  _
                    ByVal DiaVal_num As Integer,  _
                    ByVal Wc_min As Double,  _
                    ByVal Wc_max As Double,  _
                    ByVal Wc_num As Integer,  _
                    ByVal Cd As Double,  _
                    ByVal Ptr_Act As Double,  _
                    ByVal Pwh_Act As Double,  _
                    ByVal Qgi_Act As Double,  _
                    ByVal Dvalve_Act As Double,  _
                    ByVal DiaValve_Act As Double,  _
                    ByVal Wc_Act As Double,  _
                    ByVal Caso As Integer,  _
                    ByVal Metodologia As Integer) As ModelosEstabilidad.SVModel.MapaEstabilidadParametros_Estabilidad()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEstabilidad/Mapa", ReplyAction:="http://tempuri.org/IEstabilidad/MapaResponse")>  _
        Function MapaAsync( _
                    ByVal Ptr_min As Double,  _
                    ByVal Ptr_max As Double,  _
                    ByVal Ptr_num As Integer,  _
                    ByVal Pwh_Min As Double,  _
                    ByVal Pwh_Max As Double,  _
                    ByVal Pwh_num As Integer,  _
                    ByVal Qgi_min As Double,  _
                    ByVal Qgi_max As Double,  _
                    ByVal Qgi_num As Integer,  _
                    ByVal Dvalve_min As Double,  _
                    ByVal Dvalve_max As Double,  _
                    ByVal Dvalve_num As Integer,  _
                    ByVal DiaVal_min As Double,  _
                    ByVal DiaVal_max As Double,  _
                    ByVal DiaVal_num As Integer,  _
                    ByVal Wc_min As Double,  _
                    ByVal Wc_max As Double,  _
                    ByVal Wc_num As Integer,  _
                    ByVal Cd As Double,  _
                    ByVal Ptr_Act As Double,  _
                    ByVal Pwh_Act As Double,  _
                    ByVal Qgi_Act As Double,  _
                    ByVal Dvalve_Act As Double,  _
                    ByVal DiaValve_Act As Double,  _
                    ByVal Wc_Act As Double,  _
                    ByVal Caso As Integer,  _
                    ByVal Metodologia As Integer) As System.Threading.Tasks.Task(Of ModelosEstabilidad.SVModel.MapaEstabilidadParametros_Estabilidad())
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IEstabilidadChannel
        Inherits SVModel.IEstabilidad, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class EstabilidadClient
        Inherits System.ServiceModel.ClientBase(Of SVModel.IEstabilidad)
        Implements SVModel.IEstabilidad
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub DoWork() Implements SVModel.IEstabilidad.DoWork
            MyBase.Channel.DoWork
        End Sub
        
        Public Function DoWorkAsync() As System.Threading.Tasks.Task Implements SVModel.IEstabilidad.DoWorkAsync
            Return MyBase.Channel.DoWorkAsync
        End Function
        
        Public Function Recomendacion() As String Implements SVModel.IEstabilidad.Recomendacion
            Return MyBase.Channel.Recomendacion
        End Function
        
        Public Function RecomendacionAsync() As System.Threading.Tasks.Task(Of String) Implements SVModel.IEstabilidad.RecomendacionAsync
            Return MyBase.Channel.RecomendacionAsync
        End Function
        
        Public Function Pozo( _
                    ByVal Ptr_min As Double,  _
                    ByVal Ptr_max As Double,  _
                    ByVal Ptr_num As Integer,  _
                    ByVal Pwh_Min As Double,  _
                    ByVal Pwh_Max As Double,  _
                    ByVal Pwh_num As Integer,  _
                    ByVal Qgi_min As Double,  _
                    ByVal Qgi_max As Double,  _
                    ByVal Qgi_num As Integer,  _
                    ByVal Dvalve_min As Double,  _
                    ByVal Dvalve_max As Double,  _
                    ByVal Dvalve_num As Integer,  _
                    ByVal DiaVal_min As Double,  _
                    ByVal DiaVal_max As Double,  _
                    ByVal DiaVal_num As Integer,  _
                    ByVal Wc_min As Double,  _
                    ByVal Wc_max As Double,  _
                    ByVal Wc_num As Integer,  _
                    ByVal Cd As Double,  _
                    ByVal Ptr_Act As Double,  _
                    ByVal Pwh_Act As Double,  _
                    ByVal Qgi_Act As Double,  _
                    ByVal Dvalve_Act As Double,  _
                    ByVal DiaValve_Act As Double,  _
                    ByVal Wc_Act As Double,  _
                    ByVal Caso As Integer,  _
                    ByVal Metodologia As Integer) As ModelosEstabilidad.SVModel.EstabilidadDePozosParametros_Estabilidad() Implements SVModel.IEstabilidad.Pozo
            Return MyBase.Channel.Pozo(Ptr_min, Ptr_max, Ptr_num, Pwh_Min, Pwh_Max, Pwh_num, Qgi_min, Qgi_max, Qgi_num, Dvalve_min, Dvalve_max, Dvalve_num, DiaVal_min, DiaVal_max, DiaVal_num, Wc_min, Wc_max, Wc_num, Cd, Ptr_Act, Pwh_Act, Qgi_Act, Dvalve_Act, DiaValve_Act, Wc_Act, Caso, Metodologia)
        End Function
        
        Public Function PozoAsync( _
                    ByVal Ptr_min As Double,  _
                    ByVal Ptr_max As Double,  _
                    ByVal Ptr_num As Integer,  _
                    ByVal Pwh_Min As Double,  _
                    ByVal Pwh_Max As Double,  _
                    ByVal Pwh_num As Integer,  _
                    ByVal Qgi_min As Double,  _
                    ByVal Qgi_max As Double,  _
                    ByVal Qgi_num As Integer,  _
                    ByVal Dvalve_min As Double,  _
                    ByVal Dvalve_max As Double,  _
                    ByVal Dvalve_num As Integer,  _
                    ByVal DiaVal_min As Double,  _
                    ByVal DiaVal_max As Double,  _
                    ByVal DiaVal_num As Integer,  _
                    ByVal Wc_min As Double,  _
                    ByVal Wc_max As Double,  _
                    ByVal Wc_num As Integer,  _
                    ByVal Cd As Double,  _
                    ByVal Ptr_Act As Double,  _
                    ByVal Pwh_Act As Double,  _
                    ByVal Qgi_Act As Double,  _
                    ByVal Dvalve_Act As Double,  _
                    ByVal DiaValve_Act As Double,  _
                    ByVal Wc_Act As Double,  _
                    ByVal Caso As Integer,  _
                    ByVal Metodologia As Integer) As System.Threading.Tasks.Task(Of ModelosEstabilidad.SVModel.EstabilidadDePozosParametros_Estabilidad()) Implements SVModel.IEstabilidad.PozoAsync
            Return MyBase.Channel.PozoAsync(Ptr_min, Ptr_max, Ptr_num, Pwh_Min, Pwh_Max, Pwh_num, Qgi_min, Qgi_max, Qgi_num, Dvalve_min, Dvalve_max, Dvalve_num, DiaVal_min, DiaVal_max, DiaVal_num, Wc_min, Wc_max, Wc_num, Cd, Ptr_Act, Pwh_Act, Qgi_Act, Dvalve_Act, DiaValve_Act, Wc_Act, Caso, Metodologia)
        End Function
        
        Public Function Mapa( _
                    ByVal Ptr_min As Double,  _
                    ByVal Ptr_max As Double,  _
                    ByVal Ptr_num As Integer,  _
                    ByVal Pwh_Min As Double,  _
                    ByVal Pwh_Max As Double,  _
                    ByVal Pwh_num As Integer,  _
                    ByVal Qgi_min As Double,  _
                    ByVal Qgi_max As Double,  _
                    ByVal Qgi_num As Integer,  _
                    ByVal Dvalve_min As Double,  _
                    ByVal Dvalve_max As Double,  _
                    ByVal Dvalve_num As Integer,  _
                    ByVal DiaVal_min As Double,  _
                    ByVal DiaVal_max As Double,  _
                    ByVal DiaVal_num As Integer,  _
                    ByVal Wc_min As Double,  _
                    ByVal Wc_max As Double,  _
                    ByVal Wc_num As Integer,  _
                    ByVal Cd As Double,  _
                    ByVal Ptr_Act As Double,  _
                    ByVal Pwh_Act As Double,  _
                    ByVal Qgi_Act As Double,  _
                    ByVal Dvalve_Act As Double,  _
                    ByVal DiaValve_Act As Double,  _
                    ByVal Wc_Act As Double,  _
                    ByVal Caso As Integer,  _
                    ByVal Metodologia As Integer) As ModelosEstabilidad.SVModel.MapaEstabilidadParametros_Estabilidad() Implements SVModel.IEstabilidad.Mapa
            Return MyBase.Channel.Mapa(Ptr_min, Ptr_max, Ptr_num, Pwh_Min, Pwh_Max, Pwh_num, Qgi_min, Qgi_max, Qgi_num, Dvalve_min, Dvalve_max, Dvalve_num, DiaVal_min, DiaVal_max, DiaVal_num, Wc_min, Wc_max, Wc_num, Cd, Ptr_Act, Pwh_Act, Qgi_Act, Dvalve_Act, DiaValve_Act, Wc_Act, Caso, Metodologia)
        End Function
        
        Public Function MapaAsync( _
                    ByVal Ptr_min As Double,  _
                    ByVal Ptr_max As Double,  _
                    ByVal Ptr_num As Integer,  _
                    ByVal Pwh_Min As Double,  _
                    ByVal Pwh_Max As Double,  _
                    ByVal Pwh_num As Integer,  _
                    ByVal Qgi_min As Double,  _
                    ByVal Qgi_max As Double,  _
                    ByVal Qgi_num As Integer,  _
                    ByVal Dvalve_min As Double,  _
                    ByVal Dvalve_max As Double,  _
                    ByVal Dvalve_num As Integer,  _
                    ByVal DiaVal_min As Double,  _
                    ByVal DiaVal_max As Double,  _
                    ByVal DiaVal_num As Integer,  _
                    ByVal Wc_min As Double,  _
                    ByVal Wc_max As Double,  _
                    ByVal Wc_num As Integer,  _
                    ByVal Cd As Double,  _
                    ByVal Ptr_Act As Double,  _
                    ByVal Pwh_Act As Double,  _
                    ByVal Qgi_Act As Double,  _
                    ByVal Dvalve_Act As Double,  _
                    ByVal DiaValve_Act As Double,  _
                    ByVal Wc_Act As Double,  _
                    ByVal Caso As Integer,  _
                    ByVal Metodologia As Integer) As System.Threading.Tasks.Task(Of ModelosEstabilidad.SVModel.MapaEstabilidadParametros_Estabilidad()) Implements SVModel.IEstabilidad.MapaAsync
            Return MyBase.Channel.MapaAsync(Ptr_min, Ptr_max, Ptr_num, Pwh_Min, Pwh_Max, Pwh_num, Qgi_min, Qgi_max, Qgi_num, Dvalve_min, Dvalve_max, Dvalve_num, DiaVal_min, DiaVal_max, DiaVal_num, Wc_min, Wc_max, Wc_num, Cd, Ptr_Act, Pwh_Act, Qgi_Act, Dvalve_Act, DiaValve_Act, Wc_Act, Caso, Metodologia)
        End Function
    End Class
End Namespace
