'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SVDeclinacion
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SVDeclinacion.IService1")>  _
    Public Interface IService1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GethastPreTemModelo", ReplyAction:="http://tempuri.org/IService1/GethastPreTemModeloResponse")>  _
        Function GethastPreTemModelo(ByVal fecha As Date, ByVal Idagujero As String, ByVal NiveMlP_mV As Double) As System.Collections.Generic.Dictionary(Of String, Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GethastPreTemModelo", ReplyAction:="http://tempuri.org/IService1/GethastPreTemModeloResponse")>  _
        Function GethastPreTemModeloAsync(ByVal fecha As Date, ByVal Idagujero As String, ByVal NiveMlP_mV As Double) As System.Threading.Tasks.Task(Of System.Collections.Generic.Dictionary(Of String, Double))
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IService1Channel
        Inherits SVDeclinacion.IService1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1Client
        Inherits System.ServiceModel.ClientBase(Of SVDeclinacion.IService1)
        Implements SVDeclinacion.IService1
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GethastPreTemModelo(ByVal fecha As Date, ByVal Idagujero As String, ByVal NiveMlP_mV As Double) As System.Collections.Generic.Dictionary(Of String, Double) Implements SVDeclinacion.IService1.GethastPreTemModelo
            Return MyBase.Channel.GethastPreTemModelo(fecha, Idagujero, NiveMlP_mV)
        End Function
        
        Public Function GethastPreTemModeloAsync(ByVal fecha As Date, ByVal Idagujero As String, ByVal NiveMlP_mV As Double) As System.Threading.Tasks.Task(Of System.Collections.Generic.Dictionary(Of String, Double)) Implements SVDeclinacion.IService1.GethastPreTemModeloAsync
            Return MyBase.Channel.GethastPreTemModeloAsync(fecha, Idagujero, NiveMlP_mV)
        End Function
    End Class
End Namespace
