'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ModelosConfig.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Delta T a través de la bomba.
        '''</summary>
        Public ReadOnly Property BC_DACRP() As String
            Get
                Return ResourceManager.GetString("BC_DACRP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Gasto en el fondo.
        '''</summary>
        Public ReadOnly Property BC_DRATE() As String
            Get
                Return ResourceManager.GetString("BC_DRATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Gas libre en la bomba.
        '''</summary>
        Public ReadOnly Property BC_GASFREE() As String
            Get
                Return ResourceManager.GetString("BC_GASFREE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Presión de descarga de la bomba.
        '''</summary>
        Public ReadOnly Property BC_PDPRES() As String
            Get
                Return ResourceManager.GetString("BC_PDPRES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Altura de bombeo generada.
        '''</summary>
        Public ReadOnly Property BC_PHEAD() As String
            Get
                Return ResourceManager.GetString("BC_PHEAD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Presión de admisión de la bomba.
        '''</summary>
        Public ReadOnly Property BC_PINPRES() As String
            Get
                Return ResourceManager.GetString("BC_PINPRES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Requerimiento de potencia de la bomba.
        '''</summary>
        Public ReadOnly Property BC_PPR() As String
            Get
                Return ResourceManager.GetString("BC_PPR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Gasto promedio en bomba.
        '''</summary>
        Public ReadOnly Property BC_PRATE() As String
            Get
                Return ResourceManager.GetString("BC_PRATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Voltaje en superficie.
        '''</summary>
        Public ReadOnly Property BC_SVOLT() As String
            Get
                Return ResourceManager.GetString("BC_SVOLT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a %CO2 (mol).
        '''</summary>
        Public ReadOnly Property CO2() As String
            Get
                Return ResourceManager.GetString("CO2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modelo de reducción de permeabilidad por compactación.
        '''</summary>
        Public ReadOnly Property COMPACT() As String
            Get
                Return ResourceManager.GetString("COMPACT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Terminación.
        '''</summary>
        Public ReadOnly Property COMPLETION() As String
            Get
                Return ResourceManager.GetString("COMPLETION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Coeficiente térmico ajustado.
        '''</summary>
        Public ReadOnly Property CTCA() As String
            Get
                Return ResourceManager.GetString("CTCA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fecha.
        '''</summary>
        Public ReadOnly Property DATGENDATE() As String
            Get
                Return ResourceManager.GetString("DATGENDATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diam válvula de BN (64 avos pg).
        '''</summary>
        Public ReadOnly Property DIAMVAL() As String
            Get
                Return ResourceManager.GetString("DIAMVAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Factor de formación (adim).
        '''</summary>
        Public ReadOnly Property DIETZ() As String
            Get
                Return ResourceManager.GetString("DIETZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diferencial de presión a través de la válvula.
        '''</summary>
        Public ReadOnly Property DPVAL() As String
            Get
                Return ResourceManager.GetString("DPVAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reducción.
        '''</summary>
        Public ReadOnly Property DPYAC() As String
            Get
                Return ResourceManager.GetString("DPYAC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Área de drene (m2).
        '''</summary>
        Public ReadOnly Property DRAINAGE() As String
            Get
                Return ResourceManager.GetString("DRAINAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Efic. de Separador de Gas (%).
        '''</summary>
        Public ReadOnly Property EFISEPGAS() As String
            Get
                Return ResourceManager.GetString("EFISEPGAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Emulsión.
        '''</summary>
        Public ReadOnly Property EMULSION() As String
            Get
                Return ResourceManager.GetString("EMULSION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Usar RGIL o Qgi.
        '''</summary>
        Public ReadOnly Property ENTRY() As String
            Get
                Return ResourceManager.GetString("ENTRY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Etapas.
        '''</summary>
        Public ReadOnly Property ETAPAS() As String
            Get
                Return ResourceManager.GetString("ETAPAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tipo de flujo.
        '''</summary>
        Public ReadOnly Property FLOWTYPE() As String
            Get
                Return ResourceManager.GetString("FLOWTYPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fluido.
        '''</summary>
        Public ReadOnly Property FLUID() As String
            Get
                Return ResourceManager.GetString("FLUID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Coni. de Gas.
        '''</summary>
        Public ReadOnly Property GASCONING() As String
            Get
                Return ResourceManager.GetString("GASCONING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Qgi (MMpcd).
        '''</summary>
        Public ReadOnly Property GLRATE() As String
            Get
                Return ResourceManager.GetString("GLRATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a RGIL(m3/m3).
        '''</summary>
        Public ReadOnly Property GLRINY() As String
            Get
                Return ResourceManager.GetString("GLRINY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Relación Gas Aceite.
        '''</summary>
        Public ReadOnly Property GOR() As String
            Get
                Return ResourceManager.GetString("GOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Relación Gas Aceite Libre.
        '''</summary>
        Public ReadOnly Property GORFREE() As String
            Get
                Return ResourceManager.GetString("GORFREE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Qgi maximo (MMpcd).
        '''</summary>
        Public ReadOnly Property GQIMAX() As String
            Get
                Return ResourceManager.GetString("GQIMAX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ctrl. de Arenas.
        '''</summary>
        Public ReadOnly Property GRAVELPACK() As String
            Get
                Return ResourceManager.GetString("GRAVELPACK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Dens. del Gas BN.
        '''</summary>
        Public ReadOnly Property GRAVITY() As String
            Get
                Return ResourceManager.GetString("GRAVITY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a %H2S (mol).
        '''</summary>
        Public ReadOnly Property H2S() As String
            Get
                Return ResourceManager.GetString("H2S", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Coef. Transf. Calor (BTU/pie/hr/oF).
        '''</summary>
        Public ReadOnly Property HTC() As String
            Get
                Return ResourceManager.GetString("HTC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Hidratos.
        '''</summary>
        Public ReadOnly Property HYDRATE() As String
            Get
                Return ResourceManager.GetString("HYDRATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tipo de Afluencia.
        '''</summary>
        Public ReadOnly Property INFLOWTYPE() As String
            Get
                Return ResourceManager.GetString("INFLOWTYPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a IP calculada equivalente.
        '''</summary>
        Public ReadOnly Property IP() As String
            Get
                Return ResourceManager.GetString("IP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Correlación de flujo en el yacimiento.
        '''</summary>
        Public ReadOnly Property IPRMETHOD() As String
            Get
                Return ResourceManager.GetString("IPRMETHOD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Emplear permeabilidades relativas.
        '''</summary>
        Public ReadOnly Property IRELK() As String
            Get
                Return ResourceManager.GetString("IRELK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SAP.
        '''</summary>
        Public ReadOnly Property LIFTMETHOD() As String
            Get
                Return ResourceManager.GetString("LIFTMETHOD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tipo SAP.
        '''</summary>
        Public ReadOnly Property LIFTTYPE() As String
            Get
                Return ResourceManager.GetString("LIFTTYPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Longitud de Cable (m).
        '''</summary>
        Public ReadOnly Property LONGCABLE() As String
            Get
                Return ResourceManager.GetString("LONGCABLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Método de BN.
        '''</summary>
        Public ReadOnly Property METHOD() As String
            Get
                Return ResourceManager.GetString("METHOD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Factor de daño.
        '''</summary>
        Public ReadOnly Property MGSKINMETHOD() As String
            Get
                Return ResourceManager.GetString("MGSKINMETHOD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modelo de daño.
        '''</summary>
        Public ReadOnly Property MGSKINMODEL() As String
            Get
                Return ResourceManager.GetString("MGSKINMODEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a %N2 (mol).
        '''</summary>
        Public ReadOnly Property N2() As String
            Get
                Return ResourceManager.GetString("N2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diámetro de la Bomba.
        '''</summary>
        Public ReadOnly Property ODMAX() As String
            Get
                Return ResourceManager.GetString("ODMAX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Presión de salida.
        '''</summary>
        Public ReadOnly Property OUTPUTRES() As String
            Get
                Return ResourceManager.GetString("OUTPUTRES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Presión en fondo estático.
        '''</summary>
        Public ReadOnly Property PBE() As String
            Get
                Return ResourceManager.GetString("PBE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Presión en fondo fluyendo.
        '''</summary>
        Public ReadOnly Property PBF() As String
            Get
                Return ResourceManager.GetString("PBF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Presión de la TR en la válvula.
        '''</summary>
        Public ReadOnly Property PCA() As String
            Get
                Return ResourceManager.GetString("PCA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Índice de productividad (bl/día/kg/cm2).
        '''</summary>
        Public ReadOnly Property PI() As String
            Get
                Return ResourceManager.GetString("PI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Potencia del Motor.
        '''</summary>
        Public ReadOnly Property POTENCIA() As String
            Get
                Return ResourceManager.GetString("POTENCIA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Presión de Des. (Kg/cm2).
        '''</summary>
        Public ReadOnly Property PREDES() As String
            Get
                Return ResourceManager.GetString("PREDES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Predicción.
        '''</summary>
        Public ReadOnly Property PREDICT() As String
            Get
                Return ResourceManager.GetString("PREDICT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Presión del yacimiento (kg/cm2).
        '''</summary>
        Public ReadOnly Property PRES() As String
            Get
                Return ResourceManager.GetString("PRES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Profundidad de la Bomba.
        '''</summary>
        Public ReadOnly Property PROF() As String
            Get
                Return ResourceManager.GetString("PROF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Presión de fondo fluyendo (kg/cm2).
        '''</summary>
        Public ReadOnly Property PTEST() As String
            Get
                Return ResourceManager.GetString("PTEST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Presión calculada en la cabeza de la TR.
        '''</summary>
        Public ReadOnly Property PTRTEO() As String
            Get
                Return ResourceManager.GetString("PTRTEO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Presión del aparejo en la válvula.
        '''</summary>
        Public ReadOnly Property PVAL() As String
            Get
                Return ResourceManager.GetString("PVAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modelo PVT.
        '''</summary>
        Public ReadOnly Property PVTMODEL() As String
            Get
                Return ResourceManager.GetString("PVTMODEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Qgi mínimo (MMpcd).
        '''</summary>
        Public ReadOnly Property QGIMIN() As String
            Get
                Return ResourceManager.GetString("QGIMIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Gasto de líquido del aforo (bl/día).
        '''</summary>
        Public ReadOnly Property QTEST() As String
            Get
                Return ResourceManager.GetString("QTEST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Rango.
        '''</summary>
        Public ReadOnly Property RANGESYSTEM() As String
            Get
                Return ResourceManager.GetString("RANGESYSTEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Radio de Drene(m).
        '''</summary>
        Public ReadOnly Property RDRAINAGE() As String
            Get
                Return ResourceManager.GetString("RDRAINAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Permeabilidad del yacimiento (md).
        '''</summary>
        Public ReadOnly Property RESPERM() As String
            Get
                Return ResourceManager.GetString("RESPERM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a RGA (𝑚3/ 𝑚3)..
        '''</summary>
        Public ReadOnly Property RGATOTALAFORO() As String
            Get
                Return ResourceManager.GetString("RGATOTALAFORO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Separador.
        '''</summary>
        Public ReadOnly Property SEPARATOR() As String
            Get
                Return ResourceManager.GetString("SEPARATOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Daño(Adm).
        '''</summary>
        Public ReadOnly Property SKIN() As String
            Get
                Return ResourceManager.GetString("SKIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modelo Temp..
        '''</summary>
        Public ReadOnly Property TEMPMODEL() As String
            Get
                Return ResourceManager.GetString("TEMPMODEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Gasto crítico calculado.
        '''</summary>
        Public ReadOnly Property TFCAL() As String
            Get
                Return ResourceManager.GetString("TFCAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Porcentaje del gasto crítico calculado.
        '''</summary>
        Public ReadOnly Property TFPER() As String
            Get
                Return ResourceManager.GetString("TFPER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Espesor del yacimiento (m).
        '''</summary>
        Public ReadOnly Property THICKNESS() As String
            Get
                Return ResourceManager.GetString("THICKNESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Presion Cab. Dinámica (kg/cm2).
        '''</summary>
        Public ReadOnly Property THPD() As String
            Get
                Return ResourceManager.GetString("THPD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Temp. Dinámica en la Cab. del Pozo (°C).
        '''</summary>
        Public ReadOnly Property THTD() As String
            Get
                Return ResourceManager.GetString("THTD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Temp. Cab. Estática (ºC).
        '''</summary>
        Public ReadOnly Property THTE() As String
            Get
                Return ResourceManager.GetString("THTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a RGA Total(m3/m3).
        '''</summary>
        Public ReadOnly Property TOTGOR() As String
            Get
                Return ResourceManager.GetString("TOTGOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Temperatura del yacimiento (°C).
        '''</summary>
        Public ReadOnly Property TRES() As String
            Get
                Return ResourceManager.GetString("TRES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Presión Qgi (kg/cm2).
        '''</summary>
        Public ReadOnly Property TRPRES() As String
            Get
                Return ResourceManager.GetString("TRPRES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Temperatura en la válvula.
        '''</summary>
        Public ReadOnly Property TVAL() As String
            Get
                Return ResourceManager.GetString("TVAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Prof. Valv. Inyec. (m).
        '''</summary>
        Public ReadOnly Property VALVEDEPTH() As String
            Get
                Return ResourceManager.GetString("VALVEDEPTH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modelo de viscosidad.
        '''</summary>
        Public ReadOnly Property VISMOD() As String
            Get
                Return ResourceManager.GetString("VISMOD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Volumen de Gas Inyeccion.
        '''</summary>
        Public ReadOnly Property VOLGASINY() As String
            Get
                Return ResourceManager.GetString("VOLGASINY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Voltaje Superficie (V).
        '''</summary>
        Public ReadOnly Property VOLTSUP() As String
            Get
                Return ResourceManager.GetString("VOLTSUP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Viscosidad de agua.
        '''</summary>
        Public ReadOnly Property WATVIS() As String
            Get
                Return ResourceManager.GetString("WATVIS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Radio de Pozo (in).
        '''</summary>
        Public ReadOnly Property WBR() As String
            Get
                Return ResourceManager.GetString("WBR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Corte de agua(%).
        '''</summary>
        Public ReadOnly Property WC() As String
            Get
                Return ResourceManager.GetString("WC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tipo de pozo.
        '''</summary>
        Public ReadOnly Property WELLTYPE() As String
            Get
                Return ResourceManager.GetString("WELLTYPE", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
